<#
.SYNOPSIS
    Repo Map（軽量リポジトリマップ）を生成する。

.DESCRIPTION
    プロジェクト内のJavaScript/HTML/CSSファイルから関数定義、
    クラス定義、エクスポートを正規表現で抽出し、
    REPO_MAP.md として出力する。
    全コードを読み込む代わりに、このマップをLLMに送信することで
    コンテキスト消費を劇的に削減できる。

.PARAMETER ProjectRoot
    分析対象のプロジェクトルートディレクトリ（必須）
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectRoot
)

$ExcludeDirs = @('.git', 'node_modules', '.agent', '.vscode', '.gemini', '__pycache__', '.next', 'dist', 'build', 'docs')

# 出力先（docs/ サブディレクトリ内）
$DocsDir = Join-Path $ProjectRoot "docs"
if (-not (Test-Path $DocsDir)) {
    New-Item -ItemType Directory -Path $DocsDir -Force | Out-Null
}
$OutputFile = Join-Path $DocsDir "REPO_MAP.md"

function Get-JSSignatures {
    param([string]$FilePath, [string]$RelativePath)

    $signatures = @()
    try {
        $lines = Get-Content $FilePath -Encoding UTF8 -ErrorAction SilentlyContinue
    } catch {
        return $signatures
    }

    if (-not $lines) { return $signatures }

    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        $lineNum = $i + 1

        # class definition
        if ($line -match '^\s*(export\s+)?(default\s+)?class\s+(\w+)') {
            $className = $Matches[3]
            $extends = ""
            if ($line -match 'extends\s+(\w+)') {
                $extends = " extends $($Matches[1])"
            }
            $signatures += [PSCustomObject]@{
                Type = "class"
                Name = $className
                Signature = "class ${className}${extends}"
                Line = $lineNum
                File = $RelativePath
            }
        }

        # function definition (standalone)
        if ($line -match '^\s*(export\s+)?(default\s+)?(async\s+)?function\s+(\w+)\s*\(([^)]*)\)') {
            $funcName = $Matches[4]
            $params = $Matches[5].Trim()
            $asyncPrefix = if ($Matches[3]) { "async " } else { "" }
            $signatures += [PSCustomObject]@{
                Type = "function"
                Name = $funcName
                Signature = "${asyncPrefix}function ${funcName}(${params})"
                Line = $lineNum
                File = $RelativePath
            }
        }

        # arrow function / const function
        if ($line -match '^\s*(export\s+)?(const|let|var)\s+(\w+)\s*=\s*(async\s+)?\(?([^)]*)\)?\s*=>' ) {
            $funcName = $Matches[3]
            $params = $Matches[5].Trim()
            $asyncPrefix = if ($Matches[4]) { "async " } else { "" }
            $signatures += [PSCustomObject]@{
                Type = "const-fn"
                Name = $funcName
                Signature = "const ${funcName} = ${asyncPrefix}(${params}) =>"
                Line = $lineNum
                File = $RelativePath
            }
        }

        # method definition in class
        if ($line -match '^\s+(async\s+)?(\w+)\s*\(([^)]*)\)\s*\{' -and $line -notmatch '^\s*(if|for|while|switch|catch|else)') {
            $methodName = $Matches[2]
            $params = $Matches[3].Trim()
            $asyncPrefix = if ($Matches[1]) { "async " } else { "" }
            if ($methodName -ne 'function' -and $methodName -ne 'return' -and $methodName -ne 'new') {
                $signatures += [PSCustomObject]@{
                    Type = "method"
                    Name = $methodName
                    Signature = "  ${asyncPrefix}${methodName}(${params})"
                    Line = $lineNum
                    File = $RelativePath
                }
            }
        }
    }

    return $signatures
}

# Main
Write-Host "Generating Repo Map: $ProjectRoot"

$jsFiles = Get-ChildItem -Path $ProjectRoot -Recurse -File -Include @("*.js", "*.mjs", "*.ts") -ErrorAction SilentlyContinue | Where-Object {
    $dir = $_.DirectoryName
    $exclude = $false
    foreach ($d in $ExcludeDirs) {
        if ($dir -match [regex]::Escape($d)) { $exclude = $true; break }
    }
    -not $exclude
}

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$content = @()
$content += "# REPO_MAP.md"
$content += ""
$content += "> Auto-generated: $timestamp"
$content += "> Generated by: ``.agent/skills/project_analyzer/scripts/generate_repo_map.ps1``"
$content += "> "
$content += "> This is a lightweight map of all function/class signatures in the project."
$content += "> Use this instead of reading full source files to reduce context consumption."
$content += ""
$content += "---"
$content += ""

if (-not $jsFiles -or $jsFiles.Count -eq 0) {
    $content += "> No JavaScript/TypeScript files found in the project."
} else {
    foreach ($file in ($jsFiles | Sort-Object FullName)) {
        $relativePath = $file.FullName.Replace($ProjectRoot, '').TrimStart('\', '/')
        $sigs = Get-JSSignatures -FilePath $file.FullName -RelativePath $relativePath

        if ($sigs.Count -gt 0) {
            $content += "## ``$relativePath``"
            $content += ""
            $content += "| Line | Type | Signature |"
            $content += "|------|------|-----------|"
            foreach ($sig in $sigs) {
                $content += "| L$($sig.Line) | $($sig.Type) | ``$($sig.Signature)`` |"
            }
            $content += ""
        }
    }
}

$content += "---"
$content += ""
$content += "> For full architecture notes, see ``PROJECT_STRUCTURE.md``."
$content += ""

$content -join "`n" | Out-File -FilePath $OutputFile -Encoding UTF8

Write-Host "REPO_MAP.md generated: $OutputFile"
